### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by ggmartins** [noise-lab/iot-inspector-client#49] opened 2020-01-06 21:06 UTC
this is happening in the current version, the same rpi3 raspbian lite with nothing else running other than a tmux and system processes. I also tried with a fresh new clone of iot-inspector-client:
```
commit 4d1fa270151e6b5c1b9aba43d0adba090a9c343b (HEAD -> master, origin/master, origin/HEAD)
Author: Danny Y. Huang <crazyideas21@gmail.com>
Date:   Mon Jan 6 10:29:03 2020 -0500

    Fix #48
```

```
================================================================================
Time: 2020-01-06 20:51:13.479605
Function: <bound method NetdiscoWrapper._run_netdisco of <netdisco_wrapper.NetdiscoWrapper object at 0x74fa9430>> [] {}
Exception: can't start new thread
Traceback (most recent call last):
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/netdisco_wrapper.py", line 57, in _run_netdisco
    netdis.scan()
  File "/usr/local/lib/python3.7/dist-packages/netdisco/discovery.py", line 57, in scan
    self.mdns.start()
  File "/usr/local/lib/python3.7/dist-packages/netdisco/mdns.py", line 27, in start
    self.zeroconf, service.typ, service))
  File "/usr/local/lib/python3.7/dist-packages/zeroconf.py", line 1349, in __init__
    self.start()
  File "/usr/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
if I remove tcpdump, I'm still getting that error:
```
================================================================================
Time: 2020-01-06 21:00:57.339208
Function: <function sniff at 0x758c77c8> [] {'prn': <bound method PacketProcessor.process_packet of <packet_processor.PacketProcessor object at 0x759377f0>>, 'stop_filter': <function PacketCapture._capture_packets.<locals>.<lambda> at 0x74f5bc90>, 'filter': 'arp or (host not 192.168.143.23 and ether host b8:27:eb:4e:74:a1) or (port 67 or port 68)', 'timeout': 30}
Exception: tcpdump is not available. Cannot use filter !
Traceback (most recent call last):
  File "/root/princeton-iot-inspector/iot-inspector-client/v2-src/utils.py", line 246, in safe_run
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 842, in _run
    *arg, **karg)] = iface
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 475, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 160, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/common.py", line 165, in compile_filter
    raise Scapy_Exception("tcpdump is not available. Cannot use filter !")
scapy.error.Scapy_Exception: tcpdump is not available. Cannot use filter !

...


Requirement already satisfied: flask-cors in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 8)) (3.0.8)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 9)) (0.10.9)
Collecting tcpdump (from -r requirements.txt (line 10))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/tcpdump/
```

**Comment by crazyideas21** [comment] 2020-01-06 21:30
@kumarde It's a known issue. My guess is that the local Flask instance is not properly closing file descriptors. In the next release of IoT Inspector, I'll remove the local Flask instance. Stay tuned.

**Comment by crazyideas21** [comment] 2020-01-06 21:32
Related: https://github.com/noise-lab/iot-inspector-client/issues/45 and https://github.com/noise-lab/iot-inspector-client/issues/50

**Comment by ggmartins** [comment] 2020-01-07 17:14
FYI, I left it running and this morning it was dead with a "too many open files"
packet_capture.py Line 51

**Comment by crazyideas21** [comment] 2020-01-07 17:19
Thanks for the report! Will address in #50

**Comment by crazyideas21** [comment] 2020-04-07 18:45
Duplicate of #50. Closing this issue for now.

**Closed by crazyideas21** 2020-04-07 18:45 UTC
